services:
    app:
        build:
            context: .
        depends_on:
            redis:
                condition: service_healthy
            elasticsearch:
                condition: service_healthy

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    elasticsearch:
        image: 'elasticsearch:8.14.2'
        environment:
            discovery.type: 'single-node'
            xpack.security.enabled: 'false'
            ELASTICSEARCH_USERNAME: 'kibana_system'
            ELASTICSEARCH_PASSWORD: '${ELASTICSEARCH_PASSWORD}'
        ports:
            - '${FORWARD_ELASTIC_PORT:-9200}:9200'
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
        healthcheck:
            test: ['CMD-SHELL', 'curl --silent --fail http://localhost:9200/_cluster/health || exit 1']
            interval: 30s
            timeout: 10s
            retries: 50

    kibana:
        image: 'kibana:8.14.2'
        ports:
            - '${FORWARD_KIBANA_PORT:-5601}:5601'
        environment:
            ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
            XPACK_MONITORING_ENABLED: 'true'
            XPACK_MONITORING_COLLECTION_ENABLED: 'true'
            XPACK_SECURITY_ENABLED: 'false'
            ELASTICSEARCH_USERNAME: 'kibana_system'
            ELASTICSEARCH_PASSWORD: '${ELASTICSEARCH_PASSWORD}'
        depends_on:
            - 'elasticsearch'
volumes:
    redis:
    elasticsearch:
