services:
    app:
        build:
            context: .
        depends_on:
            - redis
    scheduler:
        build:
            context: .
        depends_on:
            - app
            - redis
    redis:
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
        environment:
            - REDIS_PORT_NUMBER=6379
            - ALLOW_EMPTY_PASSWORD=yes
