services:
    app:
        build:
            context: .
        networks:
            - elasticsearch
            - redis
        depends_on:
            redis:
                condition: service_healthy
            elasticsearch:
                condition: service_healthy

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis-data:/data'
        networks:
            - redis
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    elasticsearch:
        image: 'elasticsearch:8.14.2'
        environment:
            discovery.type: 'single-node'
            ELASTIC_PASSWORD: '${ELASTIC_PASSWORD:-}'
        ports:
            - '${FORWARD_ELASTIC_PORT:-9200}:9200'
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
            - elasticsearch-config:/usr/share/elasticsearch/config
        networks:
            - elasticsearch
        healthcheck:
            test: ['CMD-SHELL', 'curl --cacert /usr/share/elasticsearch/config/certs/http_ca.crt -u elastic:$ELASTIC_PASSWORD https://localhost:9200/_cluster/health || exit 1']
            interval: 30s
            timeout: 10s
            retries: 50

    kibana:
        image: 'kibana:8.14.2'
        ports:
            - '${FORWARD_KIBANA_PORT:-5601}:5601'
        networks:
            - elasticsearch
        depends_on:
            elasticsearch:
                condition: service_healthy
networks:
    elasticsearch:
    redis:
volumes:
    redis-data:
    elasticsearch-data:
    elasticsearch-config:
