services:
    app:
        build:
            target: 'production'
        ports:
            - '${PORT:-80}:80'
            - '${WEB_SERVER_PORT:-3000}:3000'
        environment:
            NODE_ENV: 'production'
    scheduler:
        build:
            context: .
            target: 'production-scheduler'
        environment:
            NODE_ENV: 'production'
volumes:
    redis:
