services:
    app:
        build:
            context: .
        depends_on:
            - redis
            - elasticsearch

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    elasticsearch:
        image: 'elasticsearch:8.14.2'
        environment:
            - discovery.type=single-node
            # Elasticsearch 8.x has HTTPS and auth on by default. This option is
            # needed to use HTTP and no auth (as used in the tests).
            - xpack.security.enabled=false
        ports:
            - '${FORWARD_ELASTIC_PORT:-9200}:9200'

    kibana:
        image: 'kibana:8.14.2'
        ports:
            - '${FORWARD_KIBANA_PORT:-5601}:5601'
        depends_on:
            - 'elasticsearch'
volumes:
    redis:
