services:
    app:
        build:
            target: 'development'
        environment:
            NODE_ENV: 'development'
        volumes:
            - .:/app

    elasticsearch:
        environment:
            # Elasticsearch 8.x has HTTPS and auth on by default. This option is
            # needed to use HTTP and no auth (as used in the tests).
            - xpack.security.enabled=false
        healthcheck:
            test: ['CMD-SHELL', 'curl --silent --fail http://localhost:9200/_cluster/health || exit 1']
            interval: 30s
            timeout: 10s
            retries: 50
