services:
  app:
    build:
      target: 'production'
    ports:
      - '${PORT:-80}:80'
    environment:
        NODE_ENV: 'production'
  scheduler:
      build:
          context: .
          target: 'production-scheduler'
      environment:
          NODE_ENV: 'production'
