services:
    app:
        build:
            target: 'development'
        ports:
            - '${PORT:-80}:80'
            - '9229:9229'
        volumes:
            - .:/app
            - /app/node_modules
