services:
    app:
        build:
            context: .
        restart: unless-stopped
        environment:
            APP_KEY: '${APP_KEY}'

            TZ: 'UTC'
            LOG_LEVEL: '${LOG_LEVEL:-info}'
            NODE_ENV: '${NODE_ENV:-production}'

            REDIS_HOST: '${REDIS_HOST:-127.0.0.1}'
            REDIS_PORT: '${REDIS_PORT:-6379}'
            REDIS_PASSWORD:

            TELEGRAM_API_ID: '${TELEGRAM_API_ID}'
            TELEGRAM_API_HASH: '${TELEGRAM_API_HASH}'

            TELEGRAM_BOT_TOKEN: '${TELEGRAM_BOT_TOKEN}'
            TELEGRAM_BOT_NAME: '${TELEGRAM_BOT_NAME}'

        depends_on:
            redis:
                condition: service_healthy

    redis:
        image: 'redis:7.2.5-alpine'
        restart: unless-stopped
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis-data:/data'
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD:-}
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

volumes:
    redis-data:
