name: Code Review

permissions:
    contents: read
    pull-requests: write

on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: anc95/ChatGPT-CodeReview@v1.0.13
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  # Optional
                  LANGUAGE: Russian
                  OPENAI_API_ENDPOINT: https://api.proxyapi.ru/openai/v1
                  MODEL: gpt-3.5-turbo
                  PROMPT: Вы опытный разработчик на NodeJS, и ваша работа — проверять Pull Request. Пожалуйста, просмотрите следующий код на предмет каких-либо недоразумений или нарушений. Не тратьте время на комментарии о том, что уже работает отлично. Жду конструктивной критики и предложений по улучшению кода, только полезные и обстоятельные замечания.
                  top_p: 1
                  temperature: 1
                  max_tokens: 10000
                  MAX_PATCH_LENGTH: 10000
