name: Run TypeScript

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - master

jobs:
    typescript:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.10.0
                  cache: 'npm'
                  cache-dependency-path: 'package-lock.json'

            - name: Cache node_modules
              id: cache-node-modules
              uses: actions/cache@v4
              with:
                  key: cache-node-modules-${{ hashFiles('package-lock.json') }}
                  path: node_modules

            - if: steps.cache-node-modules.outputs.cache-hit != 'true'
              name: Установка зависимостей npm
              shell: bash
              run: npm ci

            - name: Run TypeScript
              shell: bash
              run: npm run check:typescript
